### ISSUE TITLE
Impossible to create credentials

### ISSUE THREAD

**Issue by yecine06** [telepilotco/n8n-nodes-telepilot#6]
Hello,

I have sucessuffly installed the community plugin and i am able to add the telepilot node.

But when i try to create the credential i dont see Personal Telegram CoPilot API in the dropdown list.
I tried restarting the container but it didn't work

![Screenshot 2024-05-17 at 09 16 34](https://github.com/telepilotco/n8n-nodes-telepilot/assets/98430/6634574a-39de-4b2b-bc15-05ad97da0aef)

I am using docker install of n8n with docker composer.

```
n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data: {}
``` 

The weird thig is after i restart docker the nodes does not work anymore it's like it's not installed but in the community nodes i can still see it

![Screenshot 2024-05-17 at 09 14 38](https://github.com/telepilotco/n8n-nodes-telepilot/assets/98430/171ab0d2-ef65-49a0-ac75-050fe4e93252)

![Screenshot 2024-05-17 at 09 14 47](https://github.com/telepilotco/n8n-nodes-telepilot/assets/98430/688bbb2a-70f1-4ef5-9913-8c6e8c0f5541)

I am trying to run it on my mac with docker desktop

can you help me?

Thanks
